version: "2"

services:
  archivist:
    image: sitapati/slack-archivist:latest
    restart: always
    container_name: slack-archivist
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=slack-archivist.joshwulf.com
      - LETSENCRYPT_HOST=slack-archivist.joshwulf.com
      - LETSENCRYPT_EMAIL=josh@magikcraft.io
    volumes:
      - "./.env:/usr/src/app/dist/.env"
  # This is the network for the nginx proxy
  # See https://github.com/jwulf/letsencrypt-nginx-sidecar
networks:
  default:
    external:
      name: letsencrypt
